function options = PINN_GM_III(num)
    numEpochs             = 2^13;
    miniBatchSize         = 2^11;
    numObservationsTrain  = num;
    numIterationsPerEpoch = floor(numObservationsTrain / miniBatchSize);
    numIterations         = numEpochs * numIterationsPerEpoch;

    learnRate             = 2^-8;
    learnRateSchedule     = "plateau";
    learnRatePatience     = 1500;
    learnRateDecay        = 0.5;
    learnRateMinLearnRate = 1e-6;

    validationFrequency   = 1;

    verbose               = true;

    options = struct( ...
        "numEpochs"            , numEpochs            , ...
        "miniBatchSize"        , miniBatchSize        , ...
        "numObservationsTrain" , numObservationsTrain , ...
        "numIterationsPerEpoch", numIterationsPerEpoch, ...
        "numIterations"        , numIterations        , ...
        "learnRate"            , learnRate            , ...
        "learnRateSchedule"    , learnRateSchedule    , ...
        "learnRatePatience"    , learnRatePatience    , ...
        "learnRateDecay"       , learnRateDecay       , ...
        "learnRateMinLearnRate", learnRateMinLearnRate, ...
        "validationFrequency"  , validationFrequency  , ...
        "verbose"              , verbose                ...
    );
end