function options = PINN_GM_III(num)
    numEpochs             = 2^13;
    miniBatchSize         = 2^11;
    numObservationsTrain  = num;
    numIterationsPerEpoch = floor(numObservationsTrain / miniBatchSize);
    numIterations         = numEpochs * numIterationsPerEpoch;

    learnRate         = 2^-8;
    learnRateSchedule = presets.schedule.plateauLearnRate( ...
        1500                , ...
        "Decay"       , 0.5 , ...
        "MinDelta"    , 1e-3, ...
        "MinLearnRate", 1e-6  ...
    );

    verbose = true;

    options = struct( ...
        "numEpochs"              , numEpochs              , ...
        "miniBatchSize"          , miniBatchSize          , ...
        "numObservationsTrain"   , numObservationsTrain   , ...
        "numIterationsPerEpoch"  , numIterationsPerEpoch  , ...
        "numIterations"          , numIterations          , ...
        "learnRate"              , learnRate              , ...
        "learnRateSchedule"      , learnRateSchedule      , ...
        "verbose"                , verbose                  ...
    );
end