function options = PINN_GM_III(num)
    numEpochs             = 2^13;
    miniBatchSize         = 2^11;
    numObservationsTrain  = num;
    numIterationsPerEpoch = floor(numObservationsTrain / miniBatchSize);
    numIterations         = numEpochs * numIterationsPerEpoch;
    learnRate             = 2^-8;
    learnRateSchedule     = "piecewise";
    learnRateDropPeriod   = 2^13;
    learnRateDropFactor   = 0.5;
    verbose               = true;
    verboseFrequency      = 2^6;
    validationFrequency   = 1;
    validationPatience    = 5;

    options = struct( ...
        "numEpochs"            , numEpochs            , ...
        "miniBatchSize"        , miniBatchSize        , ...
        "numObservationsTrain" , numObservationsTrain , ...
        "numIterationsPerEpoch", numIterationsPerEpoch, ...
        "numIterations"        , numIterations        , ...
        "learnRate"            , learnRate            , ...
        "learnRateSchedule"    , learnRateSchedule    , ...
        "learnRateDropPeriod"  , learnRateDropPeriod  , ...
        "learnRateDropFactor"  , learnRateDropFactor  , ...
        "verbose"              , verbose              , ...
        "verboseFrequency"     , verboseFrequency     , ...
        "validationFrequency"  , validationFrequency  , ...
        "validationPatience"   , validationPatience     ...
    );
end