% This script preprocesses the dataset.mat file in src/data and saves the resulting data in the datastore folder.

dataset   = load("src/data/dataset.mat");

% Parameters
dataset.params  = struct();
splitPercentage = 0.99;
assert(splitPercentage > 0, 'split percentage must be greater than 0');
assert(splitPercentage < 1, 'split percentage must be less than 1');
dataset.params.splitPercentage = splitPercentage;

% Call preprocessing function preset
preprocessed = presets.PINN_GM_III(dataset);

% Saving
save("trainingData.mat", "-struct", "preprocessed"   , ...
    "trainTRJ"     , "trainACC"     , "trainPOT"     , ...
    "validationTRJ", "validationACC", "validationPOT", ...
    "params"                                           ...
);
save("metricsData.mat", "-struct", "preprocessed"                                        , ...
    "mPlanesTRJ"               , "mPlanesACC"               , "mPlanesPOT"               , ...
    "mGeneralizationTRJ_0_1"   , "mGeneralizationACC_0_1"   , "mGeneralizationPOT_0_1"   , ...
    "mGeneralizationTRJ_1_10"  , "mGeneralizationACC_1_10"  , "mGeneralizationPOT_1_10"  , ...
    "mGeneralizationTRJ_10_100", "mGeneralizationACC_10_100", "mGeneralizationPOT_10_100", ...
    "mSurfaceTRJ"              , "mSurfaceACC"              , "mSurfacePOT"              , ...
    "pPlanesTRJ"               , "pPlanesACC"               , "pPlanesPOT"               , ...
    "pGeneralizationTRJ_0_1"   , "pGeneralizationACC_0_1"   , "pGeneralizationPOT_0_1"   , ...
    "pGeneralizationTRJ_1_10"  , "pGeneralizationACC_1_10"  , "pGeneralizationPOT_1_10"  , ...
    "pGeneralizationTRJ_10_100", "pGeneralizationACC_10_100", "pGeneralizationPOT_10_100", ...
    "pSurfaceTRJ"              , "pSurfaceACC"              , "pSurfacePOT"                ...
);

clearvars -except DO_DATA_EXTRACTION DO_PREPROCESSING DO_TRAINING DO_TESTING